drone_position: "2.25 -16.5 6.5"
drone_orientation: "-1.57 0.0 0.0"
water_jerlow: "0.20"
seafloor_position: "0.0 0.0 3.0"
seafloor_orientation: "1.57 0.0 0.0"
structure_position: "1.0 -18.0 8.1"
structure_orientation: "-1.57 0.0 -1.57"
